Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2020-10, with the labels that each got.

#339 Chore/omit fedora 30
  .travis.yml
Labels: CI/CD

#336 Fix/issue 335
  engine/CMakeLists.txt
  engine/src/cmd/basecomputer.cpp
  engine/src/cmd/collision.cpp
  engine/src/cmd/damageable.h
  engine/src/cmd/drawable.h
  engine/src/cmd/movable.cpp
  engine/src/cmd/movable.h
  engine/src/cmd/unit_generic.cpp
  engine/src/cmd/unit_generic.h
  engine/src/gfx/background.cpp
  engine/src/gfx/vdu.cpp
  engine/src/gfxlib_struct.h
  engine/src/gldrv/gl_light.cpp
  engine/src/gldrv/gl_light_state.cpp
  engine/src/star_system.h
  engine/src/vs_globals.h
Labels: bug

#330 Task refactor units
  engine/CMakeLists.txt
  engine/src/cmd/ai/fire.cpp
  engine/src/cmd/asteroid.cpp
  engine/src/cmd/asteroid.h
  engine/src/cmd/asteroid_generic.cpp
  engine/src/cmd/asteroid_generic.h
  engine/src/cmd/atmosphere.cpp
  engine/src/cmd/base_interface.cpp
  engine/src/cmd/basecomputer.cpp
  engine/src/cmd/building.cpp
  engine/src/cmd/building.h
  engine/src/cmd/building_generic.cpp
  engine/src/cmd/building_generic.h
  engine/src/cmd/collision.cpp
  engine/src/cmd/dummy_unit.cpp
  engine/src/cmd/dummy_unit.h
  engine/src/cmd/enhancement.h
  engine/src/cmd/enhancement_generic.h
  engine/src/cmd/missile.cpp
  engine/src/cmd/missile.h
  engine/src/cmd/nebula.cpp
  engine/src/cmd/nebula.h
  engine/src/cmd/nebula_generic.cpp
  engine/src/cmd/nebula_generic.h
  engine/src/cmd/planet.cpp
  engine/src/cmd/planet.h
  engine/src/cmd/planet_generic.cpp
  engine/src/cmd/planet_generic.h
  engine/src/cmd/script/script_call_unit.cpp
  engine/src/cmd/script/script_call_unit_generic.cpp
  engine/src/cmd/unit.cpp
  engine/src/cmd/unit.h
  engine/src/cmd/unit_generic.h
  engine/src/cmd/unit_generics.h
  engine/src/cmd/unit_template.h
  engine/src/cmd/unit_util.cpp
  engine/src/cmd/unit_util_generic.cpp
  engine/src/gfx/cockpit.cpp
  engine/src/gfx/mesh.cpp
  engine/src/gfx/mesh_gfx.cpp
  engine/src/gfx/radar/sensor.cpp
  engine/src/gfx/radar/track.cpp
  engine/src/main_loop.cpp
  engine/src/star_system.cpp
  engine/src/star_system_xml.cpp
  engine/src/system_factory.cpp
Labels: enhancement

#320 Refactor: get rid of opcodegarray macro
  engine/src/cmd/collide2/CSopcodecollider.cpp
  engine/src/cmd/collide2/CSopcodecollider.h
  engine/src/cmd/collide2/Stdafx.h
  engine/src/cmd/collide2/basecollider.h
  engine/src/vs_collections.hpp
Labels: Compiler_Warnings, enhancement
