Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2020-06, with the labels that each got.

#139 Create FUNDING.yml
  .github/FUNDING.yml
Labels: enhancement

#140 [skip ci] Refactor README.md
  README.md
Labels: enhancement

#135 Enhancement: CPack Support
  .gitignore
  .travis.yml
  README.md
  engine/CMakeLists.txt
  sh/vspackage.sh
Labels: Proposal, enhancement

#148 Bug Fix: Change master Packaging version to 0.7.0
  engine/CMakeLists.txt
Labels: bug

#147 Enhancement packaging 0.6.x
  .gitignore
  .travis.yml
  README.md
  engine/CMakeLists.txt
  sh/vspackage.sh
Labels: enhancement

#150 Revert "Refactor (Q)Vector"
  engine/CMakeLists.txt
  engine/src/aldrv/al_globals.h
  engine/src/cmd/ai/aggressive.cpp
  engine/src/cmd/ai/autodocking.h
  engine/src/cmd/terrain.h
  engine/src/cmd/unit.h
  engine/src/gfx/aux_logo.h
  engine/src/gfx/matrix.h
  engine/src/gfx/mesh_server.cpp
  engine/src/gfx/nav/navscreen.h
  engine/src/gfx/tvector.cpp
  engine/src/gfx/tvector.h
  engine/src/gfx/vec.cpp
  engine/src/gfx/vec.h
  engine/src/gfx/xvector.h
  engine/src/savegame.h
  engine/src/vsfilesystem.h
Labels: bug

#146 Enhancement: Added notes for contributors regarding packaging
  CONTRIBUTING.rst
Labels: enhancement

#121 Remove python related cs_ files
  engine/src/cmd/ai/pythonai.cpp
  engine/src/cmd/ai/pythonai.h
  engine/src/cmd/base_init.cpp
  engine/src/cmd/base_interface.cpp
  engine/src/cmd/base_util.cpp
  engine/src/cmd/base_util.h
  engine/src/cmd/base_xml.cpp
  engine/src/cmd/script/director.cpp
  engine/src/cmd/script/director_generic.cpp
  engine/src/cmd/script/director_server.cpp
  engine/src/cmd/script/mission.cpp
  engine/src/cmd/script/pythonmission.cpp
  engine/src/cmd/script/script_call_unit.cpp
  engine/src/command.cpp
  engine/src/cs_boostpython.h
  engine/src/cs_boostpythonclass.h
  engine/src/cs_boostpythonobj.h
  engine/src/cs_python.h
  engine/src/gfx/tvector.cpp
  engine/src/main.cpp
  engine/src/python/init.cpp
  engine/src/python/init.h
  engine/src/python/python_class.h
  engine/src/python/python_compile.h
  engine/src/savegame.cpp
  engine/src/star_system_generic.cpp
  engine/src/universe_util_generic.cpp
Labels: enhancement
