Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2020-04, with the labels that each got.

#44 Enhancement: std::(isfinite, isnan)
  engine/src/vs_math.h
Labels: bug

#51 Bug Fixes
  engine/src/cmd/collide2/Ice/IcePoint.h
  engine/src/vs_math.h
Labels: bug

#43 Enhancement: Testing more OS configurations
  .travis.yml
Labels: CI/CD, enhancement

#67 Add Gitter Badge
  README.md
Labels: enhancement

#65 (refactor) Fix clang compilation
  .travis.yml
  engine/setup/src/include/central.cpp
  engine/setup/src/include/display_gtk.cpp
  engine/setup/src/include/file.cpp
  engine/setup/src/include/general.cpp
  engine/src/aldrv/al_sound.cpp
  engine/src/audio/renderers/OpenAL/OpenALRenderer.cpp
  engine/src/gfx/cockpit.cpp
  engine/src/gfx/nav/navitemstodraw.h
  engine/src/gldrv/gl_light_state.cpp
  engine/src/gldrv/hashtable_3d.h
Labels: CI/CD, bug

#70 Update: Version to 0.6.0
  doc/man/vegastrike.1
  engine/setup/src/include/display.h
  engine/vegastrike.spec
  sh/vsinstall.sh
Labels: enhancement

#80 Fixed -Wcatch-value warnings
  engine/src/audio/RenderableListener.cpp
  engine/src/audio/RenderableSource.cpp
  engine/src/audio/Source.cpp
  engine/src/audio/Stream.cpp
  engine/src/audio/TemplateManager.cpp
  engine/src/audio/codecs/OggCodec.cpp
  engine/src/audio/renderers/OpenAL/OpenALRenderableStreamingSource.cpp
  engine/src/audio/renderers/OpenAL/OpenALSimpleSound.cpp
  engine/src/audio/renderers/OpenAL/OpenALStreamingSound.cpp
  engine/src/audio/test.cpp
  engine/src/cmd/base_util.cpp
  engine/src/command.cpp
  engine/src/gfx/ani_texture.cpp
  engine/src/gfx/mesh_gfx.cpp
  engine/src/gfx/technique.cpp
  engine/src/gfx/vid_file.cpp
  engine/src/gfx/vsimage.cpp
  engine/src/star_system_generic.cpp
Labels: CI/CD
