Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2020-07, with the labels that each got.

#165 Port vegasettings to GTK3
  .travis.yml
  README.md
  engine/CMakeLists.txt
  engine/FindGTK2.cmake
  engine/FindGTK3.cmake
  engine/setup/CMakeLists.txt
  engine/setup/src/include/central.cpp
  engine/setup/src/include/central.h
  engine/setup/src/include/display_gtk.cpp
Labels: enhancement

#163 Correct boost::python component specification wrt boost 1.67+
  engine/CMakeLists.txt
Labels: bug

#174 CMake: Improve debug optimization in C/C++ debug config
  engine/CMakeLists.txt
Labels: enhancement

#186 vsfilesystem.cpp: Fixes potential path buffer overflows
  engine/src/vsfilesystem.cpp
Labels: bug

#193 Fixed Travis CD
  .travis.yml
Labels: bug, enhancement

#144 A new replacement class GameConfig based on boost xml parser
  engine/CMakeLists.txt
  engine/src/cmd/planet.cpp
  engine/src/game_config.cpp
  engine/src/game_config.h
  engine/src/vsfilesystem.cpp
Labels: Proposal, enhancement

#194 Fix/bouncing bug
  engine/src/cmd/ai/aggressive.cpp
  engine/src/cmd/ai/fire.cpp
  engine/src/cmd/ai/flybywire.cpp
  engine/src/cmd/ai/ikarus.cpp
  engine/src/cmd/ai/navigation.cpp
  engine/src/cmd/ai/turretai.cpp
  engine/src/cmd/beam_generic.cpp
  engine/src/cmd/bolt_generic.cpp
  engine/src/cmd/briefing.cpp
  engine/src/cmd/collide.cpp
  engine/src/cmd/collide_map.cpp
  engine/src/cmd/cont_terrain.cpp
  engine/src/cmd/missile.h
  engine/src/cmd/missile_generic.cpp
  engine/src/cmd/mount.cpp
  engine/src/cmd/nebula.cpp
  engine/src/cmd/planet_generic.cpp
  engine/src/cmd/script/director.cpp
  engine/src/cmd/terrain.cpp
  engine/src/cmd/unit.cpp
  engine/src/cmd/unit_collide.cpp
  engine/src/cmd/unit_generic.cpp
  engine/src/cmd/unit_physics.h
  engine/src/cmd/unit_util_generic.cpp
  engine/src/gfx/ani_texture.cpp
  engine/src/gfx/cockpit.cpp
  engine/src/gfx/tvector.cpp
  engine/src/gfx/tvector.h
  engine/src/lin_time.cpp
  engine/src/star_system.cpp
  engine/src/star_system_generic.cpp
  engine/src/universe_util_generic.cpp
  engine/src/vegastrike.h
  engine/src/vsfilesystem.cpp
Labels: bug

#200 Backport cmake install targets
  engine/CMakeLists.txt
  engine/objconv/CMakeLists.txt
  engine/setup/CMakeLists.txt
Labels: bug

#172 Boost log to file
  engine/src/cmd/ai/script.cpp
  engine/src/cmd/basecomputer.cpp
  engine/src/cmd/bolt_generic.cpp
  engine/src/cmd/csv.cpp
  engine/src/cmd/missile_generic.cpp
  engine/src/cmd/role_bitmask.cpp
  engine/src/cmd/script/director.cpp
  engine/src/cmd/script/mission.cpp
  engine/src/cmd/unit_generic.cpp
  engine/src/configxml.cpp
  engine/src/easydom.h
  engine/src/gamemenu.cpp
  engine/src/gfx/mesh_xml.cpp
  engine/src/gldrv/winsys.cpp
  engine/src/main.cpp
  engine/src/python/init.cpp
  engine/src/savegame.cpp
  engine/src/star_system_generic.cpp
  engine/src/stardate.cpp
  engine/src/vsfilesystem.cpp
  engine/src/vsfilesystem.h
Labels: enhancement

#203 Add .deb dependencies for the Debian and Ubuntu releases that we know how to build on
  engine/CMakeLists.txt
Labels: CI/CD, bug

#206 .deb dependencies, unique filenames on master
  engine/CMakeLists.txt
Labels: CI/CD, bug

#181 Task xml refactor
  engine/CMakeLists.txt
  engine/mission/include/easydom.h
  engine/setup/src/include/display_gtk.cpp
  engine/src/audio/CodecRegistry.cpp
  engine/src/cmd/base_xml.cpp
  engine/src/cmd/cont_terrain.h
  engine/src/cmd/faction_xml.cpp
  engine/src/cmd/planet_generic.cpp
  engine/src/cmd/planet_generic.h
  engine/src/cmd/script/director.cpp
  engine/src/cmd/script/director_generic.cpp
  engine/src/cmd/terrain.h
  engine/src/cmd/unit_generic.cpp
  engine/src/galaxy.cpp
  engine/src/galaxy.h
  engine/src/galaxy_utils.cpp
  engine/src/gfx/radar/viewarea.cpp
  engine/src/gfxlib_struct.h
  engine/src/star_system.cpp
  engine/src/star_system.h
  engine/src/star_system_generic.cpp
  engine/src/star_system_generic.h
  engine/src/star_system_xml.cpp
  engine/src/star_xml.h
  engine/src/system_factory.cpp
  engine/src/system_factory.h
  engine/src/vsfilesystem.cpp
  engine/src/vsfilesystem.h
Labels: bug, enhancement

#202 Fix/Bug 154
  README.md
  engine/CMakeLists.txt
  sh/vsbuild.sh
Labels: bug
