Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2020-09, with the labels that each got.

#322 Fixes a compiler warning in vegasettings/src/include/general.cpp
  engine/setup/src/include/general.cpp
Labels: Compiler_Warnings

#325 Move reactToCollision code to its own class
  engine/CMakeLists.txt
  engine/src/cmd/asteroid_generic.cpp
  engine/src/cmd/asteroid_generic.h
  engine/src/cmd/collision.cpp
  engine/src/cmd/collision.h
  engine/src/cmd/enhancement_generic.h
  engine/src/cmd/missile.h
  engine/src/cmd/missile_generic.cpp
  engine/src/cmd/missile_generic.h
  engine/src/cmd/movable.cpp
  engine/src/cmd/nebula_generic.cpp
  engine/src/cmd/nebula_generic.h
  engine/src/cmd/planet.cpp
  engine/src/cmd/planet.h
  engine/src/cmd/planet_generic.h
  engine/src/cmd/unit_collide.cpp
  engine/src/cmd/unit_generic.cpp
  engine/src/cmd/unit_generic.h
  engine/src/cmd/unit_type.h
  engine/src/game_config.h
  engine/src/gfx/tvector.h
Labels: bug, enhancement

#326 Compiler fixes round 5
  engine/objconv/mesher/to_BFXM.cpp
  engine/objconv/mesher/to_BFXM.h
  engine/src/cmd/weapon_xml.cpp
  engine/src/cmd/weapon_xml.h
  engine/src/gfx/mesh_xml.cpp
  engine/src/gfxlib_struct.h
  engine/src/gldrv/gl_light_state.cpp
Labels: bug
