Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2020-05, with the labels that each got.

#90 Removed support of Ubuntu 14.04 LTS
  .travis.yml
Labels: CI/CD, question

#89 Add full py2/py3 configuration to CMake build config
  README.md
  engine/CMakeLists.txt
Labels: enhancement

#127 Contributing guidelines for the 0.6.x branch
  CONTRIBUTING.rst
Labels: enhancement

#124 Contributor Guidelines: First draft
  CONTRIBUTING.rst
Labels: enhancement

#126 Bug Fix: Add authors file for 0.6.x
  AUTHORS
  sh/build-authors.sh
Labels: bug

#125 Enhancement: Auto-generating the AUTHORS file
  AUTHORS
  sh/build-authors.sh
Labels: bug

#129 Pull Request Template
  .github/pull_request_template.md
Labels: enhancement

#132 Pull Request Template
  .github/pull_request_template.md
Labels: bug, enhancement

#133 Enhancement: Standardize CMakeLists.txt
  engine/CMakeLists.txt
  engine/objconv/CMakeLists.txt
  engine/objconv/mesher/CMakeLists.txt
  engine/setup/CMakeLists.txt
Labels: enhancement

#134 Enhancement: Standardize CMakeLists.txt
  engine/CMakeLists.txt
  engine/objconv/CMakeLists.txt
  engine/objconv/mesher/CMakeLists.txt
  engine/setup/CMakeLists.txt
Labels: enhancement
