Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2020-08, with the labels that each got.

#210 In basecomputer.cpp, convert all instances of sprintf to use boost::format instead
  engine/src/cmd/basecomputer.cpp
Labels: bug

#197 Some more refactoring in July
  engine/CMakeLists.txt
  engine/src/cmd/ai/aggressive.cpp
  engine/src/cmd/ai/fire.cpp
  engine/src/cmd/ai/flybywire.cpp
  engine/src/cmd/ai/flyjoystick.cpp
  engine/src/cmd/ai/navigation.cpp
  engine/src/cmd/ai/script.cpp
  engine/src/cmd/basecomputer.cpp
  engine/src/cmd/computer.cpp
  engine/src/cmd/computer.h
  engine/src/cmd/damageable.cpp
  engine/src/cmd/damageable.h
  engine/src/cmd/drawable.cpp
  engine/src/cmd/drawable.h
  engine/src/cmd/movable.cpp
  engine/src/cmd/movable.h
  engine/src/cmd/planet_generic.cpp
  engine/src/cmd/planet_generic.h
  engine/src/cmd/planetary_orbit.cpp
  engine/src/cmd/planetary_orbit.h
  engine/src/cmd/unit.h
  engine/src/cmd/unit_damage.h
  engine/src/cmd/unit_generic.cpp
  engine/src/cmd/unit_generic.h
  engine/src/cmd/unit_util_generic.cpp
  engine/src/cmd/vs_limits.h
  engine/src/gfx/cockpit.cpp
  engine/src/main_loop.cpp
  engine/src/python/unit_wrapper_class.h
  engine/src/ship_commands.cpp
  engine/src/star_system.cpp
  engine/src/star_system_xml.cpp
  engine/src/system_factory.cpp
Labels: enhancement

#219 Fix/segfault on ship purchase
  engine/src/cmd/basecomputer.cpp
  engine/src/cmd/unit.cpp
  engine/src/cmd/unit_generic.cpp
  engine/src/gfx/mesh_gfx.cpp
  engine/src/gfxlib_struct.cpp
  engine/src/gfxlib_struct.h
  engine/src/main.cpp
  engine/src/star_system_generic.cpp
  engine/src/star_xml.h
Labels: bug

#215 openSUSE build requirements
  .travis.yml
  README.md
  engine/CMakeLists.txt
Labels: CI/CD, enhancement

#221 CPack: vsUTCS => Vega-Strike
  engine/CMakeLists.txt
Labels: CI/CD, enhancement

#261 Fixes a compile error by removing an out of date ifdef
  engine/src/gldrv/gl_texture.cpp
Labels: Compiler_Warnings, bug

#217 vsfilesystem.cpp: Fix potential path buffer overflows on 0.6.x
  engine/src/vsfilesystem.cpp
Labels: bug

#224 Fix/segfault on missile discharged
  engine/src/SharedPool.h
  engine/src/cmd/missile_generic.cpp
Labels: bug

#265 Fixes the two enums being compared to booleans
  engine/src/cmd/ai/hard_coded_scripts.cpp
  engine/src/cmd/unit_generic.cpp
Labels: Compiler_Warnings, enhancement

#264 A few easy fixes sprinkled all around
  engine/src/cmd/damageable.cpp
  engine/src/cmd/drawable.cpp
  engine/src/cmd/planetary_orbit.cpp
  engine/src/cmd/unit_generic.cpp
  engine/src/galaxy_gen.cpp
  engine/src/gfx/mesh_fx.cpp
  engine/src/gfx/nav/navscreen.cpp
  engine/src/gfx/vdu.cpp
  engine/src/load_mission.cpp
  engine/src/rendertext.cpp
  engine/src/system_factory.cpp
Labels: Compiler_Warnings, enhancement

#268 Rename entire CMake project from 'vsUTCS' to 'Vega_Strike'
  engine/CMakeLists.txt
  engine/objconv/CMakeLists.txt
  engine/objconv/mesher/CMakeLists.txt
  engine/setup/CMakeLists.txt
Labels: CI/CD, bug

#276 Rename entire CMake project from 'vsUTCS' to 'Vega_Strike'
  engine/CMakeLists.txt
  engine/objconv/CMakeLists.txt
  engine/objconv/mesher/CMakeLists.txt
  engine/setup/CMakeLists.txt
Labels: CI/CD, bug

#277 On Travis, build in Debug configuration, except for tags/releases
  .travis.yml
  sh/travis-build.sh
  sh/vsbuild.sh
Labels: CI/CD, enhancement

#278 Packaging for openSUSE Leap 15.2 and Fedora 32; etc.
  README.md
  engine/CMakeLists.txt
Labels: CI/CD, enhancement

#284 Add Ubuntu 20.04 Focal support to Travis-CI
  .travis.yml
Labels: CI/CD, enhancement

#285 Normalize shell scripts
  .travis.yml
  README.md
  script/bootstrap
  script/build-authors.sh
  script/build.sh
  script/buildmac.sh
  script/buildrpm
  script/cibuild
  script/clean
  script/compile
  script/install
  script/intel-mac-conf.sh
  script/makerelease.sh
  script/package
  script/setup
  script/vssetup-gtk+osx.sh
  sh/travis-build.sh
Labels: CI/CD, enhancement

#275 Compiler fixes 2
  engine/objconv/asteroidgen.cpp
  engine/src/cmd/beam_generic.cpp
  engine/src/cmd/drawable.cpp
  engine/src/cmd/music.cpp
  engine/src/faction_generic.cpp
  engine/src/faction_generic.h
  engine/src/gfx/aux_texture.cpp
  engine/src/gfxlib_struct.h
  engine/src/gldrv/gl_globals.h
  engine/src/gldrv/gl_state.cpp
  engine/src/star_system_xml.cpp
Labels: Compiler_Warnings, enhancement

#288 Compiler fixes 3
  engine/src/cmd/planet_generic.cpp
  engine/src/cmd/unit_csv.cpp
  engine/src/gfx/star.cpp
Labels: Compiler_Warnings, enhancement

#291 Add docker stuff, and use it in Travis CI. Update scripts as needed
  .dockerignore
  .travis.yml
  Dockerfile
  engine/CMakeLists.txt
  engine/src/game_config.cpp
  engine/src/game_config.h
  script/bootstrap
  script/cibuild
  script/docker-entrypoint.sh
  script/setup
Labels: CI/CD, enhancement

#295 Dockerize 2
  .travis.yml
  Dockerfile
  script/cibuild
Labels: CI/CD, enhancement

#313 Fix/cppcheck warnings, etc.
  .gitignore
  engine/CMakeLists.txt
  engine/launcher/general.cpp
  engine/launcher/general.h
  engine/launcher/saveinterface.cpp
  engine/mission/include/easydom.h
  engine/mission/include/general.cpp
  engine/objconv/MeshParse/template_generator.cpp
  engine/objconv/asteroidgen.cpp
  engine/objconv/basemaker/sprite.cpp
  engine/objconv/imageproc/normalmap.cpp
  engine/objconv/starsystemgen/starsysgen.cpp
  engine/setup/src/include/general.cpp
  engine/src/aldrv/al_sound.cpp
  engine/src/audio/SoundBuffer.cpp
  engine/src/cmd/collide2/CSopcodecollider.cpp
  engine/src/cmd/collide2/Ice/IcePoint.h
  engine/src/cmd/collide2/opcodegarray.h
  engine/src/cmd/collide2/opcodesysdef.h
  engine/src/cmd/script/director_generic.cpp
  engine/src/cmd/unit_util_generic.cpp
  engine/src/cmd/weapon_xml.cpp
  engine/src/command.cpp
  engine/src/configxml.cpp
  engine/src/galaxy_gen.cpp
  engine/src/gfx/nav/navpath.cpp
  engine/src/gfx/vsimage.h
  engine/src/gldrv/gl_quad_list.cpp
  engine/src/python/python_class.h
  engine/src/vsfilesystem.cpp
  engine/vs_cubemap_gen/src/filter/filter_impl/filter_one_texel.cpp
  engine/vs_cubemap_gen/src/filter/filter_impl/filter_settings.cpp
  engine/vs_cubemap_gen/src/texture/mem_texture_impl/coords.cpp
  engine/vs_cubemap_gen/src/texture/mem_texture_impl/coords.h
  engine/vs_cubemap_gen/src/texture/texture_settings.h
Labels: CI/CD, Compiler_Warnings, enhancement
