Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2020-12, with the labels that each got.

#352 fix segfault post player death by checking for null unit in getAnger etc
  engine/src/cmd/pilot.cpp
  engine/src/cmd/unit_util_generic.cpp
Labels: bug

#347 Update version to 0.8.x
  doc/man/vegastrike.1
  engine/CMakeLists.txt
  engine/setup/src/include/display.h
  engine/src/main.cpp
  engine/vegastrike.spec
  script/install
Labels: enhancement

#348 Travis config: Enable deployment configuration; add Fedora 33
  .travis.yml
  engine/CMakeLists.txt
Labels: CI/CD

#361 Enable packaging - master
  .travis.yml
  engine/CMakeLists.txt
Labels: CI/CD

#365 Fix Travis CD logic on master
  .travis.yml
  script/package
Labels: CI/CD, bug

#363 Oops, forgot that script/package is already run by script/cibuild
  .travis.yml
  script/package
Labels: CI/CD

#374 engine/CMakeLists.txt: Add libglu1-mesa as buster install dependency
  engine/CMakeLists.txt
Labels: Installer, bug

#371 Retire py2 builds
  .travis.yml
  Dockerfile
  engine/CMakeLists.txt
Labels: CI/CD, enhancement

#375 engine/CMakeLists.txt: Add libglu1-mesa as buster install dependency
  engine/CMakeLists.txt
Labels: Installer, bug

#377 engine/CMakeLists.txt: Add libglu1-mesa as bionic install dependency
  engine/CMakeLists.txt
Labels: Installer, bug
