Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2021-12, with the labels that each got.

#613 script/build.sh: Improve handling of paths and parameters with spaces
  script/build.sh
Labels: bug

#614 Enhancement engine py version api 0 8 x
  engine/CMakeLists.txt
  engine/setup/src/include/display.h
  engine/src/cmd/engineVersion.cpp
  engine/src/cmd/engineVersion.h
  engine/src/main.cpp
  engine/src/python/init.cpp
  engine/src/python/unit_wrapper.cpp
Labels: enhancement

#616 Peer Review: Remove duplication
  engine/CMakeLists.txt
Labels: bug

#615 Change location of .vegastrike folder on Windows - 0.8.x
  .github/workflows/Windows-CI.yml
  .github/workflows/codeql.yml
  README.md
  engine/CMakeLists.txt
  engine/src/main.cpp
  engine/src/savegame.cpp
  engine/src/universe_util_generic.cpp
  engine/src/vs_globals.h
  engine/src/vsfilesystem.cpp
  engine/src/vsfilesystem.h
  script/cibuild
Labels: enhancement, Compiler_Warnings

#625 glvnd on RPM-based distros; Impish; Fedora 35; etc.
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
  engine/CMakeLists.txt
  script/bootstrap
Labels: bug, CI/CD, Installer

#619 Fix issue preventing player from dying
  engine/src/cmd/damageable.cpp
Labels: bug

#618 Change location of .vegastrike folder on Windows - master
  .github/workflows/Windows-CI.yml
  .github/workflows/codeql.yml
  README.md
  engine/CMakeLists.txt
  engine/src/vs_globals.h
  engine/src/vsfilesystem.cpp
Labels: enhancement

#617 Enhancement: Asset API change log documentation
  doc/ASSET_API.rst
Labels: enhancement

#626 Fix Installer Description and README - 0.8.x
  README.md
  engine/CMakeLists.txt
Labels: Installer

#628 CPack: Instead of hard-coding x86_64 in package filenames, use CPACK_…
  engine/CMakeLists.txt
Labels: enhancement, CI/CD, Installer
