Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2021-01, with the labels that each got.

#380 engine/CMakeLists.txt: Supply CPACK_PACKAGE_DESCRIPTION, as text value
  engine/CMakeLists.txt
Labels: Installer, bug

#379 engine/CMakeLists.txt: Add libglu1-mesa as bionic install dependency
  engine/CMakeLists.txt
Labels: Installer, bug

#383 Chore/GitHub Actions, including CodeQL analysis
  .github/workflows/codeql-analysis.yml
Labels: CI/CD, enhancement

#384 Chore/GH Actions build matrix
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .travis.yml
  script/cibuild
Labels: CI/CD, enhancement

#385 Chore/GH Actions on master
  .github/workflows/ci.yml
  .travis.yml
  script/cibuild
Labels: CI/CD, enhancement

#386 GH Actions - Enable CD on 0.7.x
  .github/workflows/ci.yml
  README.md
  engine/CMakeLists.txt
  script/cibuild
  script/docker-entrypoint.sh
Labels: CI/CD, enhancement

#392 Let's try this again (GH Actions CD)
  .github/workflows/ci.yml
Labels: CI/CD, bug

#393 Chore/GH Actions CD Try Again
  .github/workflows/ci.yml
  script/cibuild
  script/docker-entrypoint.sh
Labels: CI/CD, Installer, bug

#395 CPack: Add libboost-date-time1.58.0 as apt dependency for Ubuntu bionic
  engine/CMakeLists.txt
Labels: Installer, bug

#394 Bugfix 0.7.x gh actions
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
  script/cibuild
  script/docker-entrypoint.sh
Labels: CI/CD, bug

#398 CPack: Add libboost-date-time1.58.0 as dependency for bionic .deb's
  engine/CMakeLists.txt
Labels: Installer, bug

#396 Create fortify-on-demand-scan.yml
  .github/workflows/fortify-on-demand-scan.yml
Labels: CI/CD, enhancement

#397 Add codeql.yml back in
  .github/workflows/codeql.yml
Labels: CI/CD, enhancement

#400 GH Actions - Release: Troubleshoot CD further
  .github/workflows/gh-actions-release.yml
Labels: CI/CD, bug

#399 Chore/GH Actions CD on master
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
  README.md
  engine/CMakeLists.txt
  script/cibuild
  script/docker-entrypoint.sh
Labels: CI/CD, bug, enhancement

#402 CD: GH Actions - Release: Omit source from deployed artifacts (0.7.x series)
  .github/workflows/gh-actions-release.yml
Labels: CI/CD, bug

#404 Chore/More on GH Actions - master
  .github/workflows/gh-actions-release.yml
  engine/CMakeLists.txt
  script/cibuild
Labels: CI/CD, Installer, bug, enhancement

#403 CD: GH Actions - Release: Try a different way of including only .deb's & .rpm's
  .github/workflows/gh-actions-release.yml
  engine/CMakeLists.txt
Labels: CI/CD, Installer, enhancement

#407 Fix/ARTIFACT_EXT Syntax
  .github/workflows/gh-actions-release.yml
Labels: CI/CD, bug

#409 Drop engine/datascripts/makeloki.sh
  engine/datascripts/makeloki.sh
Labels: enhancement

#408 GH Actions - Release: Fix ARTIFACT_EXT for source build
  .github/workflows/gh-actions-release.yml
Labels: CI/CD, bug

#410 Fix/ARTIFACT_EXT on master
  .github/workflows/gh-actions-release.yml
Labels: CI/CD, bug

#412 Enhancement: Updating the manpage
  doc/man/vegastrike.1
Labels: enhancement

#413 Enhancement updating the manpage 0 8 x
  doc/man/vegastrike.1
Labels: enhancement
