Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2021-03, with the labels that each got.

#432 Bug Fix: Legacy Data Directory Mode Support
  doc/man/CMakeLists.txt
  doc/man/vegasettings.1
  doc/man/vegastrike-engine.1
  doc/man/vsinstall.1
  doc/man/vslauncher.1
  engine/CMakeLists.txt
  engine/src/main.cpp
  engine/src/vsfilesystem.cpp
  script/build.sh
  script/buildmac.sh
  script/buildrpm
  script/install
  script/package
Labels: bug

#433 Bugfix legacy support default directory specification 0 7 x
  doc/man/CMakeLists.txt
  doc/man/vegasettings.1
  doc/man/vegastrike-engine.1
  doc/man/vsinstall.1
  doc/man/vslauncher.1
  engine/CMakeLists.txt
  engine/src/main.cpp
  engine/src/vsfilesystem.cpp
  script/build.sh
  script/buildmac.sh
  script/buildrpm
  script/install
  script/package
Labels: bug, enhancement

#435 Enhancement: Re-enable dynamic dependency detection
  engine/CMakeLists.txt
Labels: bug, enhancement

#437 CPack: Introduce BOOST_VER variable; fix libboost-* deps manually
  engine/CMakeLists.txt
Labels: Installer, bug

#436 fix segfault post player death by checking for null unit in getAnger etc
  engine/src/cmd/pilot.cpp
  engine/src/cmd/unit_util_generic.cpp
Labels: bug

#438 Update the CMakelists.txt to find the actual ChangeLog on 0.7.x
  doc/CMakeLists.txt
Labels: Installer, bug

#439 CPack: Introduce BOOST_VER variable; fix libboost-* deps manually (on master)
  engine/CMakeLists.txt
Labels: Installer, bug
