Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2021-06, with the labels that each got.

#462 More on Windows CI - 0.8.x
  .github/workflows/Windows-CI.yml
  engine/setup/CMakeLists.txt
  engine/vcpkg.json
  script/build.ps1
Labels: CI/CD, enhancement

#467 script/build.ps1: Add /y argument to xcopy commands
  script/build.ps1
Labels: enhancement

#463 Utf-8 check, C++ initial version
  engine/src/cmd/basecomputer.cpp
  engine/src/cmd/script/director_generic.cpp
  engine/src/savegame.cpp
  engine/src/savegame.h
Labels: bug

#465 general.cpp: Implement ptr_copy as specified in issue 430
  engine/setup/src/include/general.cpp
Labels: Compiler_Warnings

#471 Backport 463 0.8.x
  engine/src/cmd/basecomputer.cpp
  engine/src/cmd/script/director_generic.cpp
  engine/src/savegame.cpp
  engine/src/savegame.h
Labels: bug

#473 Backport 470 0.8.x
  engine/src/cmd/basecomputer.cpp
Labels: bug

#477 Windows CI: Add dependency caching
  .github/workflows/Windows-CI.yml
Labels: CI/CD, enhancement

#475 Refactor weapon_xml into weapon_factory and other classes (2)
  engine/CMakeLists.txt
  engine/src/cmd/ai/firekeyboard.cpp
  engine/src/cmd/ai/hard_coded_scripts.cpp
  engine/src/cmd/armed.cpp
  engine/src/cmd/basecomputer.cpp
  engine/src/cmd/beam.cpp
  engine/src/cmd/beam.h
  engine/src/cmd/beam_generic.cpp
  engine/src/cmd/bolt.cpp
  engine/src/cmd/bolt.h
  engine/src/cmd/faction_factory.cpp
  engine/src/cmd/faction_factory.h
  engine/src/cmd/faction_xml.cpp
  engine/src/cmd/mount.cpp
  engine/src/cmd/mount_size.cpp
  engine/src/cmd/mount_size.h
  engine/src/cmd/role_bitmask.cpp
  engine/src/cmd/unit.cpp
  engine/src/cmd/unit_collide.cpp
  engine/src/cmd/unit_csv.cpp
  engine/src/cmd/unit_functions_generic.cpp
  engine/src/cmd/unit_generic.cpp
  engine/src/cmd/unit_generic.h
  engine/src/cmd/unit_util_generic.cpp
  engine/src/cmd/unit_xml.cpp
  engine/src/cmd/weapon_factory.cpp
  engine/src/cmd/weapon_factory.h
  engine/src/cmd/weapon_info.cpp
  engine/src/cmd/weapon_info.h
  engine/src/cmd/weapon_type.cpp
  engine/src/cmd/weapon_type.h
  engine/src/cmd/weapon_xml.cpp
  engine/src/cmd/weapon_xml.h
  engine/src/gfx/cockpit.cpp
  engine/src/gfx/cockpit_generic.cpp
  engine/src/gfx/vdu.cpp
  engine/src/python/unit_wrapper.cpp
  engine/src/universe.cpp
Labels: enhancement
