Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2021-09, with the labels that each got.

#536 On master, drop Ubuntu 16.04 "Xenial" LTS and Debian 9 "stretch"
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
  engine/CMakeLists.txt
  script/bootstrap
  script/build-authors.sh
  script/build.sh
  script/cibuild
  script/clean
  script/docker-entrypoint.sh
  script/install
  script/makerelease.sh
  script/package
  script/setup
Labels: CI/CD

#537 CMake Minimum Required Version 3.11
  .gitignore
  engine/CMakeLists.txt
  engine/FindMATH.deprecated.cmake
  script/bootstrap.ps1
  script/build.ps1
Labels: enhancement

#539 Add unit tests
  .github/workflows/Windows-CI.yml
  .github/workflows/gh-actions-pr.yml
  .github/workflows/macos-ci.yml
  engine/CMakeLists.txt
  engine/src/configuration/tests/configuration_tests.cpp
  script/build.ps1
  script/build.sh
  script/cibuild
  script/docker-entrypoint.sh
Labels: enhancement, CI/CD

#542 README.md: Fix (mostly minor) markdown linting issues, etc.
  README.md
Labels: enhancement

#549 Change the `Fortify on Demand Scan` to run only when manually triggered
  .github/workflows/fortify-on-demand-scan.yml
Labels: CI/CD

#552 Change the `Fortify on Demand Scan` to run only when manually triggered - 0.8.x branch
  .github/workflows/fortify-on-demand-scan.yml
Labels: CI/CD

#551 Fix/CodeQL Warnings 2021-09 (Part 1)
  engine/src/cmd/jump_capable.cpp
  engine/src/main.cpp
  engine/src/savegame.cpp
  engine/src/universe_util_generic.cpp
  engine/src/vs_globals.h
  engine/src/vsfilesystem.cpp
  engine/src/vsfilesystem.h
Labels: bug, Compiler_Warnings

#553 Bug Fix: properly detect DEB package tooling
  engine/CMakeLists.txt
  engine/FindLinuxDistro.cmake
Labels: bug, enhancement

#557 GLVND option on Linux, etc.
  .github/workflows/Windows-CI.yml
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
  engine/CMakeLists.txt
  engine/vcpkg.json
  script/bootstrap
  script/cibuild
Labels: bug, enhancement

#576 Fix Windows CI (python3 build)
  .github/workflows/Windows-CI.yml
Labels: bug, CI/CD, Compiler Error

#540 cmd/collision.cpp: Make it so that Nav 8 cannot be crashed into
  .gitignore
  engine/src/cmd/collision.cpp
  engine/src/savegame.cpp
  engine/src/savegame.h
Labels: bug
