Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2022-02, with the labels that each got.

#643 find python3 directly
  engine/CMakeLists.txt
Labels: enhancement, CI/CD

#650 Fix build issues with Boost 1.78 on windows by reverting to Boost 1.77 (alternate approach)
  .github/workflows/Windows-CI.yml
  engine/vcpkg.json
Labels: bug, CI/CD, Compiler Error

#651 CMakeLists.txt: Remove -funsafe-math-optimizations; set CMAKE_MINIMUM…
  engine/CMakeLists.txt
Labels: bug, enhancement

#652 Cap # of CPU cores used to build the code
  .github/workflows/codeql.yml
  README.md
  engine/saveinterface/build
  script/build
  script/cibuild
  script/docker-entrypoint.sh
Labels: enhancement, CI/CD

#654 GH Actions, scripts, CMakeLists.txt: Port #625 and other 0.8 changes to `master`
  .dockerignore
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
  .gitignore
  engine/CMakeLists.txt
  script/bootstrap
  script/build
  script/cibuild
  script/docker-entrypoint.sh
Labels: enhancement, CI/CD, Installer
