Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2024-12, with the labels that each got.

#932 Stephen's December 2024 updates to macOS CI for 0.9.x
  .github/workflows/macos-ci.yml
  .github/workflows/macos-release.yml
  engine/CMakeLists.txt
Labels: CI/CD, Installer, Compiler Error

#891 Maintenance: Updated Supported MacOS versions
  .github/workflows/macos-ci.yml
  engine/CMakeLists.txt
  script/bootstrap-mac.sh
  script/cibuild
Labels: CI/CD

#940 macOS Releases: Fix Packaging Step (0.9.x)
  .github/workflows/macos-release.yml
Labels: CI/CD, Installer

#942 More On Packaging - 0.9.x
  .github/workflows/macos-ci.yml
  .github/workflows/macos-release.yml
  engine/CMakeLists.txt
Labels: bug, CI/CD, Installer

#943 Fix CPack package filenames; try to get one Windows installer working
  .github/workflows/Windows-Release.yml
  .github/workflows/macos-release.yml
  engine/CMakeLists.txt
Labels: bug, enhancement, Installer
