Repository vegastrike/Vega-Strike-Engine-Source, pull requests merged in 2025-01, with the labels that each got.

#947 Include Third-Party Dependencies In Installers - 0.9.x
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
  doc/CMakeLists.txt
  doc/man/CMakeLists.txt
  engine/CMakeLists.txt
  engine/CMakePresets.json
  engine/objconv/CMakeLists.txt
  engine/objconv/mesher/CMakeLists.txt
  engine/setup/CMakeLists.txt
  script/bootstrap
  script/bootstrap.ps1
  script/clean
Labels: bug, Installer

#953 Fix macOS installer - 0.9.x
  engine/CMakeLists.txt
  engine/setup/CMakeLists.txt
Labels: bug, Installer

#955 2x CMakeLists.txt: More fixes for macOS installer package
  engine/CMakeLists.txt
  engine/setup/CMakeLists.txt
Labels: bug, Installer

#957 Yet more on macOS installer - 0.9.x
  .github/workflows/Windows-Release.yml
  engine/CMakeLists.txt
  engine/CMakePresets.json
  engine/setup/CMakeLists.txt
  script/build.ps1
  script/package.ps1
  script/test.ps1
Labels: Installer

#965 winsys.cpp: Actually exit the game in winsys_exit() (Fix Issue 961, with minimal code changes)
  engine/src/gldrv/winsys.cpp
Labels: bug

#964 unit_csv.cpp: Fix parsing of "Yaw_Governor_Right" and "Yaw_Governor_Left"
  engine/src/cmd/unit_csv.cpp
Labels: bug

#967 Switch Vega Strike 0.9.x over to use boost::program_options
  .github/workflows/macos-ci.yml
  .github/workflows/macos-release.yml
  engine/CMakeLists.txt
  engine/CMakePresets.json
  engine/setup/CMakeLists.txt
  engine/setup/src/c/setup.cpp
  engine/src/gfx/ani_texture.h
  engine/src/lin_time.cpp
  engine/src/main.cpp
  engine/vcpkg.json
  script/bootstrap-on-macOS-using-MacPorts.sh
  script/bootstrap-on-macos.sh
  script/build
Labels: enhancement

#975 Python version wrangling 0.9.x
  .github/workflows/Windows-CI.yml
  .github/workflows/Windows-Release.yml
  .github/workflows/codeql.yml
  .github/workflows/fortify-on-demand-scan.yml
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
  .github/workflows/macos-ci.yml
  .github/workflows/macos-release.yml
  .github/workflows/scorecards-analysis.yml
  engine/CMakeLists.txt
  engine/CMakePresets.json
Labels: CI/CD, Compiler Error

#976 Remove setting PYTHONHOME for Windows builds
  script/bootstrap.ps1
Labels: bug, CI/CD

#982 Enhancement: Minimize Download Size
  README.md
Labels: bug, enhancement

#985 Fix installer description paragraph - 0.9.x
  README.md
  engine/CMakeLists.txt
Labels: bug, Installer

#986 Update installer description paragraph, README, a few other things - 0.10.x
  CMakeLists.txt
  README.md
  engine/CMakeLists.txt
Labels: bug, Installer

#987 Fix some crashes 2025-01-13
  .github/workflows/gh-actions-pr.yml
  engine/src/cmd/basecomputer.cpp
  engine/src/cmd/collide2/CSopcodecollider.cpp
  engine/src/cmd/collide2/Stdafx.h
  engine/src/cmd/controls_factory.cpp
  engine/src/cmd/damageable.cpp
  engine/src/cmd/unit_csv.cpp
  engine/src/cmd/unit_generic.cpp
  engine/src/cmd/unit_json_factory.cpp
  engine/src/components/component_utils.cpp
  engine/src/gfx/cockpit.cpp
  engine/src/gfx/mesh_gfx.cpp
  engine/src/gfx/vdu.cpp
  engine/src/gfxlib.h
  engine/src/gldrv/gl_texture.cpp
  engine/src/python/config/python_utils.cpp
  engine/src/python/config/python_utils.h
  engine/src/python/infra/get_string.cpp
  engine/src/python/init.cpp
  engine/src/vs_vector.h
  engine/src/vsfilesystem.cpp
  engine/src/xml_support.h
Labels: bug

#999 Refactor vegastrike-engine and vegasettings to use boost::program_options -- 0.10.x
  CMakeLists.txt
  engine/CMakeLists.txt
  engine/objconv/CMakeLists.txt
  engine/objconv/mesher/CMakeLists.txt
  engine/setup/src/c/setup.cpp
  engine/src/main.cpp
Labels: enhancement

#998 Fix Issue #997
  engine/src/cmd/csv.cpp
  engine/src/cmd/csv.h
  engine/src/cmd/unit_csv.cpp
  engine/src/cmd/unit_json_factory.cpp
Labels: bug

#1017 Update actions/upload-artifact from v3 to v4 in two workflow files th…
  .github/workflows/gh-actions-pr.yml
  .github/workflows/scorecards-analysis.yml
Labels: bug, CI/CD
